<?php

/**
 * @file
 * Gallery custom module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_page_attachments().
 */
function gallery_custom_page_attachments(array &$attachments) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  
  // Add custom CSS to gallery page
  if (strpos($route_name, 'view.index_gallery') === 0) {
    $attachments['#attached']['library'][] = 'porto/gallery_custom';
  }
}
